# The time to wait before giving the reminder in seconds.
reminderTime: 14400

# String, the time to display in-game, eg: 300 seconds = 5 minutes, 3600 seconds = 1 hour..
display: 4 hours

# Whether to publicly send a message when a player hits the reminderTime or not
public-shaming: false