name: TouchGrassReminder-plugin
version: '${project.version}'
main: me.goodbee.touchgrassreminderplugin.TouchGrassReminder
api-version: '1.19'
load: POSTWORLD

commands:
  touchgrass:
    description: "test"